# Generated by Django 3.0.3 on 2020-02-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='', verbose_name='conteudo'),
        ),
    ]
