# Generated by Django 3.0.3 on 2020-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='', max_length=280, verbose_name='conteudo'),
        ),
    ]
