# Generated by Django 3.0.3 on 2020-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200205_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
